articles/urls.py
from django.urls import path

from .views import(
    article_search_views,
    article_create_view,
    article_detail_view   
)

app_name = 'articles'
urlpatterns = [
    path('',article_search_views,name='search'),
    path('create/',article_create_view,  name='create'),
    path('<slug:slug>/',article_detail_view, name='detail'),
]

recipes/urls.py
from django.urls import path

from .views import (
    recipe_list_view,
    recipe_detail_view,
    recipe_delete_view,
    recipe_create_view,
    recipe_update_view,
    recipe_detail_hx_view,
    recipe_ingrdient_update_hx_view,
    recipe_ingredient_delete_view,
    recipe_ingredient_image_upload_view
)

app_name = 'recipes'

urlpatterns =[
    path("",recipe_list_view, name='list'),
    path("create/", recipe_create_view , name='create'),
    
    path("hx/<int:parent_id>/ingredient/<int:id>/", recipe_ingrdient_update_hx_view , name='hx-ingredient-detail'),
    path("hx/<int:parent_id>/ingredient/", recipe_ingrdient_update_hx_view , name='hx-ingredient-create'),
    path("hx/<int:id>/", recipe_detail_hx_view , name='hx-detail'),
    
    path("<int:parent_id>/image-upload/", recipe_ingredient_image_upload_view ),
    
    path("<int:parent_id>/ingredient/<int:id>/delete/", recipe_ingredient_delete_view , name='ingredient-delete'),
    path("<int:id>/delete/", recipe_delete_view , name='delete'),
    path("<int:id>/edit/", recipe_update_view, name='update'),
    path("<int:id>/", recipe_detail_view , name='detail'),
]

trydjango/urls.py
from django.contrib import admin
from django.urls import include,path,re_path

from accounts.views import (
    login_view,
    logout_view,
    register_view
)

from articles.views import(
   
    article_create_view,
    article_detail_view
)

from search.views import search_view
from .views import home_view

urlpatterns = [
    path('',home_view),#index/ home / root
    path('pantry/recipes/',include('recipes.urls')),
    path('articles/',include('articles.urls')),
    path('search/',search_view, name='search'),
    # path('articles/',article_search_views),
    # path('articles/create/',article_create_view,  name='article-create'),
    # path('articles/<slug:slug>/',article_detail_view, name='article-detail'),
    path('admin/', admin.site.urls),
    path('login/',login_view),
    path('logout/',logout_view),
    path('register/',register_view),
    
]
 

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <script src="https://unpkg.com/htmx.org@1.9.7"
            integrity="sha384-EAzY246d6BpbWR7sQ8+WEm40J8c3dHFsqC58IgPlh4kMbRRI6P6WA+LA/qGAyAu8"
            crossorigin="anonymous"></script>
        
        <link rel="stylesheet" href="{% static "recipes/recipes-htmx.css" %}" />

    </head>
    <body>
        <h1>HELLO WORLD!</h1>
        {% include 'search/search-form.html'%}
        
        {% block content %}
        <h3>This will be replaced.</h3>
        {% endblock content %}

        <script>
            document.body.addEventListener("htmx:configRequest",(event)=>{event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}'
        })
        </script>
        
    </body>
</html>

templates/home-view.html
{%extends "base.html" %}

{% block content %}
<h1>{{object.title}} (id: {{ id }})!</h1>
<p> {{content}}</p>

<a href="{%url 'articles:create' %}">create article</a>
<a href="{% url 'articles:detail' slug='sanatan-rakshak' %}">Hello world article</a>

<ul>
    {% for x in object_list %}
        {% if x.title %}
            <li><a href = '{{x.get_absolute_url }}'>{{x.title}} - {{x.content}}</li>
        {% endif %}
    {% endfor %}
</ul>
{% endblock content %}

templates/image-form.html
{% extends "base.html" %}


{% block content %}



<div style="margin-top: 30px;">
    <form action="." method="POST" enctype="multipart/form-data" 
    hx-post = "{{ request.path }}"
    hx-enctype="multipart/form-data" 
    >
        {% csrf_token %}
        {{form.as_p}}

       

        <div><button type="submit">Upload Image
        </button></div>

    </form>
</div>


{% endblock content %}